// Generated by jextract

package org.openjdk.jextract.clang.libclang;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

import static org.openjdk.jextract.clang.libclang.FFMUtils.*;
import static org.openjdk.jextract.clang.libclang.LayoutUtils.*;

/**
 * {@snippet lang=c :
 * struct CXUnsavedFile {
 *     const char *Filename;
 *     const char *Contents;
 *     unsigned long Length;
 * }
 * }
 */
public class CXUnsavedFile {

    CXUnsavedFile() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("Filename"),
        C_POINTER.withName("Contents"),
        C_LONG.withName("Length"),
        MemoryLayout.paddingLayout(4)
    ).withName("CXUnsavedFile");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout Filename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Filename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static final AddressLayout Filename$layout() {
        return Filename$LAYOUT;
    }

    private static final long Filename$OFFSET = $LAYOUT.byteOffset(groupElement("Filename"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static final long Filename$offset() {
        return Filename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static MemorySegment Filename(MemorySegment struct) {
        return struct.get(Filename$LAYOUT, Filename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static void Filename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Filename$LAYOUT, Filename$OFFSET, fieldValue);
    }

    private static final AddressLayout Contents$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Contents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static final AddressLayout Contents$layout() {
        return Contents$LAYOUT;
    }

    private static final long Contents$OFFSET = $LAYOUT.byteOffset(groupElement("Contents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static final long Contents$offset() {
        return Contents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static MemorySegment Contents(MemorySegment struct) {
        return struct.get(Contents$LAYOUT, Contents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static void Contents(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Contents$LAYOUT, Contents$OFFSET, fieldValue);
    }

    private static final OfInt Length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("Length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static final OfInt Length$layout() {
        return Length$LAYOUT;
    }

    private static final long Length$OFFSET = $LAYOUT.byteOffset(groupElement("Length"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static final long Length$offset() {
        return Length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static int Length(MemorySegment struct) {
        return struct.get(Length$LAYOUT, Length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static void Length(MemorySegment struct, int fieldValue) {
        struct.set(Length$LAYOUT, Length$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

